#!/usr/bin/env bash
# **** License ****
#
# Copyright (C) 2017 by Helmrock Consulting
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# **** End License ****
#
# Author: Neil Beadle
# Adds RFC2136 DDNS templates to the EdgeOS based Edge Routers

export COPY_EXTENDED_ATTRIBUTES_DISABLE=true
export COPYFILE_DISABLE=true

VERSION=$(cat VERSION)
NAME='ddns_rfc2136'
RFC2136="${NAME}.v${VERSION}"
INSTALL="install_${RFC2136}"
PAYLOAD='payload'
SED='gsed -i.bak '
SEDCMD='s/Copyright (C) 20../Copyright (C) '$(date +"%Y")'/g'
SEDVER='s/^VERSION=.*$/VERSION=\"'${VERSION}'\"/g'
UPDATE_VARS=("${PAYLOAD}/installer" "${PAYLOAD}/Remove_RFC2136.sh" decompress LICENSE)


if [ -e "${0##*/}" ]; then
	BASEDIR=`pwd`
	[[ -f ${RFC2136}setup.tgz ]] && rm ${RFC2136}setup.tgz
	cd ${PAYLOAD}
	tar zcf ../${PAYLOAD}.tgz --exclude='._*' --exclude='.svn' --exclude='.DS_Store' --exclude='*.bak' --exclude='*~' ./*
	cd ..

	if [ -e "${PAYLOAD}.tgz" ]; then

		for i in ${UPDATE_VARS[@]}
		do
			if [[ -f "${i}" ]]
			then
				# Update Copyright to current year
				eval ${SED} \'${SEDCMD}\' ${i}
				eval ${SED} \'${SEDVER}\' ${i}
			fi
		done
		cat decompress ${PAYLOAD}.tgz >> ${INSTALL}

	else
		echo "${PAYLOAD}.tgz does not exist"
		exit 1
	fi

	chmod 0755 "${INSTALL}"
	tar zcf ${INSTALL}.tgz ${INSTALL}
	echo "${INSTALL} created"
	cd ..
	tar -zcf ${INSTALL}.tgz --exclude='._*' --exclude='.svn' --exclude='.DS_Store' --exclude='*.bak' --exclude='*~' $BASEDIR/*
	mv ${INSTALL}.tgz ${BASEDIR}/
	cd ${BASEDIR}

# scp the build to our test router for debugging
	[[ ${1} ]] && /usr/bin/scp -i ~/.ssh/jeff_id_rsa "${BASEDIR}"/${INSTALL} ${1}@unms-server:/tmp/${INSTALL}
else
	echo "$(basename $0) must be run in the directory where it is located."
fi
exit 0
