#!/usr/bin/env bash
#
# **** License ****
#
# Copyright (C) 2017 by Helmrock Consulting
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# **** End License ****
#
# Author: Neil Beadle
# Adds RFC2136 DDNS templates to the EdgeOS based Edge Routers

VERSION="1.2"

echo -ne "Self Extracting Installer for Dynamic DNS (DDNS) RFC 2136 v${VERSION} support\n\n"

CDIR=$(pwd)

# Make sure script is run as ubnt admin
if [[ ${EUID} -eq 0 ]]; then
	echo 'This script must be run as the ubnt admin user, not root!'
	exit 1
fi

install_menu ()
{
	local IFS=' '
	local PS3='Enter option number and hit return => '
	local OPTIONS=('INSTALL' 'REMOVE' 'PURGE' 'QUIT')
	shopt -s checkwinsize
	local COLUMNS=$(tput cols)

while true;
do
	echo -ne "Would you like to INSTALL, REMOVE, PURGE or QUIT?\n\n" | fold -s -w ${COLUMNS}
	select CHOICE in ${OPTIONS[@]}; do
		case ${REPLY} in
			1)	clear console
					echo "Installing RFC 2136 DDNS support"
					./setup
					break
					return 1
					;;
			2)	clear console
					./Remove_RFC2136.sh
					break
					;;
			3)	clear console
					sudo ./ubnt-cln-cfg-orphans.sh
					break
					;;
			4|*)	return 0
					;;
		esac
	done
done
}

export TMPDIR=`mktemp -d /tmp/selfextract.XXXXXX`

ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`

tail -n+${ARCHIVE} $0 | tar xz -C ${TMPDIR}

cd ${TMPDIR}

install_menu

cd ${CDIR}
sudo rm -rf ${TMPDIR}

exit 0

__ARCHIVE_BELOW__
